In [9]:
import requests
import json
import pandas as pd

## Get basic data about players and gameweeks

In [6]:
response = requests.get('https://fantasy.allsvenskan.se/api/bootstrap-static/')

In [7]:
with open('data/pre-season/raw/bootstrap-static.json', 'w+') as json_file:
    json.dump(response.json(), json_file)

## Get all players detailed data

In [46]:
data = response.json();
player_data = pd.DataFrame(data['elements'])
player_data.sample(5)

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,...,saves,own_goals,attacking_bonus,defending_bonus,winning_goals,crosses,key_passes,big_chances_created,clearances_blocks_interceptions,recoveries
215,NaN,None,81651,0,0,0,0,0,3,1.0,...,0,0,0,8,0,0,11,0,47,107
387,NaN,None,177884,0,0,0,0,0,2,2.0,...,0,0,2,33,0,6,18,1,146,195
76,0.0,None,39725,0,0,0,0,0,1,0.0,...,0,0,0,0,0,0,0,0,0,0
207,NaN,None,94660,0,0,0,0,0,2,2.0,...,0,0,2,25,0,0,11,2,157,113
54,NaN,None,244993,0,0,0,0,0,2,1.0,...,0,0,0,0,0,0,0,0,0,0

In [47]:
player_data.shape[0]

417

In [45]:
from IPython.display import clear_output

df_height = player_data.shape[0]

for index, player in player_data.iterrows():
    player_id = str(player['id'])
    first_name = player['first_name']
    last_name = player['second_name']
    
    
    clear_output(wait=True)
    print(f'Getting player {player_id} {first_name} {last_name} (Total: {df_height})')

    player_response = requests.get(f'https://fantasy.allsvenskan.se/api/element-summary/{player_id}/')
    
    file_name = f"{player_id.rjust(3, '0')}_{first_name}_{last_name}".replace(' ', '_')
    with open(f'data/pre-season/raw/players/{file_name}.json', 'w+') as player_file:
        json.dump(player_response.json(), player_file)
        
clear_output(wait=True)
print('Done!')

Done!