In [1]:
import requests
import json
import pandas as pd

## Get basic data about players and gameweeks

In [2]:
response = requests.get('https://fantasy.allsvenskan.se/api/bootstrap-static/')

In [3]:
with open('data/during-season/bootstrap-static.json', 'w+') as json_file:
    json.dump(response.json(), json_file, indent=2)

## Get all players detailed data

In [4]:
data = response.json();
player_data = pd.DataFrame(data['elements'])
player_data.head(5)

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,...,saves,own_goals,attacking_bonus,defending_bonus,winning_goals,crosses,key_passes,big_chances_created,clearances_blocks_interceptions,recoveries
0,NaN,NaN,52251,0,0,0,0,0,1,5.8,...,11,0,0,0,0,0,0,0,36,33
1,NaN,NaN,531041,0,0,0,0,0,1,0.0,...,0,0,0,0,0,0,0,0,0,0
2,0.0,0.0,50448,0,0,-1,1,0,2,0.0,...,0,0,0,0,0,0,0,0,0,0
3,100.0,100.0,82187,0,0,0,0,0,2,0.0,...,0,0,0,0,0,0,0,0,0,0
4,NaN,NaN,54433,1,-1,3,-3,0,2,6.6,...,0,0,0,8,0,1,0,0,75,40

In [5]:
player_data.shape

(435, 55)

In [6]:
from IPython.display import clear_output

df_height = player_data.shape[0]

for index, player in player_data.iterrows():
    player_id = str(player['id'])
    first_name = player['first_name']
    last_name = player['second_name']
    
    
    clear_output(wait=True)
    print(f'Getting players ({player_id}/{df_height}) {first_name} {last_name}')

    player_response = requests.get(f'https://fantasy.allsvenskan.se/api/element-summary/{player_id}/')
    
    file_name = f"{player_id.rjust(3, '0')}_{first_name}_{last_name}".replace(' ', '_')
    with open(f'data/during-season/players/{file_name}.json', 'w+') as player_file:
        json.dump(player_response.json(), player_file, indent=2)
        
clear_output(wait=True)
print(f'Done! Got {df_height} players.')

Done! Got 435 players.