In [1]:
import requests
import json
import pandas as pd

## Get basic data about players and gameweeks

In [3]:
response = requests.get('https://fantasy.allsvenskan.se/api/bootstrap-static/')

In [4]:
with open('data/during-season/bootstrap-static.json', 'w+') as json_file:
    json.dump(response.json(), json_file, indent=2)

## Get all players detailed data

In [5]:
data = response.json();
player_data = pd.DataFrame(data['elements'])
player_data.sample(5)

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,...,saves,own_goals,attacking_bonus,defending_bonus,winning_goals,crosses,key_passes,big_chances_created,clearances_blocks_interceptions,recoveries
38,NaN,NaN,471248,0,0,0,0,0,3,0.5,...,0,0,0,0,0,0,0,0,0,0
160,NaN,NaN,157743,0,0,0,0,0,3,3.0,...,0,0,1,1,0,2,2,0,17,15
149,NaN,NaN,135414,0,0,0,0,0,2,3.0,...,0,0,1,0,0,3,3,2,4,3
298,NaN,NaN,524029,0,0,0,0,0,3,0.0,...,0,0,0,0,0,0,0,0,0,0
260,0.0,0.0,479379,0,0,0,0,0,2,0.0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
player_data.shape

(432, 55)

In [8]:
from IPython.display import clear_output

df_height = player_data.shape[0]

for index, player in player_data.iterrows():
    player_id = str(player['id'])
    first_name = player['first_name']
    last_name = player['second_name']
    
    
    clear_output(wait=True)
    print(f'Getting players ({player_id}/{df_height}) {first_name} {last_name}')

    player_response = requests.get(f'https://fantasy.allsvenskan.se/api/element-summary/{player_id}/')
    
    file_name = f"{player_id.rjust(3, '0')}_{first_name}_{last_name}".replace(' ', '_')
    with open(f'data/during-season/players/{file_name}.json', 'w+') as player_file:
        json.dump(player_response.json(), player_file, indent=2)
        
clear_output(wait=True)
print(f'Done! Got {df_height} players.')

Done!